config/routes.rb
Depot::Application.routes.draw do
  get 'admin' => 'admin#index'
  controller :sessions do
    get  'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
  scope '(:locale)' do
    resources :users
    resources :orders
    resources :line_items
    resources :carts
    resources :products do
      get :who_bought, :on => :member
    end
    root :to => 'store#index', :as => 'store'
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pragprog Books Online Store</title>
<!-- START:stylesheet -->
  <%= stylesheet_link_tag "scaffold" %>
  <%= stylesheet_link_tag "depot", :media => "all" %><!-- <label id="code.slt"/> -->
<!-- END:stylesheet -->
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %><!-- <label id="code.csrf"/> -->
</head>
<body id="store">
  <div id="banner">
  	
<!-- START_HIGHLIGHT -->
    <%= form_tag store_path, :class => 'locale' do %>
<!-- END_HIGHLIGHT -->
      <%= select_tag 'set_locale', 
        options_for_select(LANGUAGES, I18n.locale.to_s),
        :onchange => 'this.form.submit()' %>
      <%= submit_tag 'submit' %>
      <%= javascript_tag "$$('.locale input').each(Element.hide)" %>
<!-- START_HIGHLIGHT -->
    <% end %>
<!-- END_HIGHLIGHT -->

    <%= image_tag("logo.png") %>
<!-- START_HIGHLIGHT -->
    <%= @page_title || t('.title') %>
<!-- END_HIGHLIGHT -->
  </div>
  <div id="columns">
    <div id="side">
<!-- START_HIGHLIGHT -->
      <% if @cart %>
<!-- END_HIGHLIGHT -->
        <%= hidden_div_if(@cart.line_items.empty?, :id => "cart") do %>
          <%= render @cart %>
        <% end %>
<!-- START_HIGHLIGHT -->
      <% end %>
<!-- END_HIGHLIGHT -->
    	
<!-- START_HIGHLIGHT -->
      <a href="http://www...."><%= t('.home') %></a><br />
<!-- END_HIGHLIGHT -->
<!-- START_HIGHLIGHT -->
      <a href="http://www..../faq"><%= t('.questions') %></a><br />
<!-- END_HIGHLIGHT -->
<!-- START_HIGHLIGHT -->
      <a href="http://www..../news"><%= t('.news') %></a><br />
<!-- END_HIGHLIGHT -->
<!-- START_HIGHLIGHT -->
      <a href="http://www..../contact"><%= t('.contact') %></a><br />
<!-- END_HIGHLIGHT -->

<!-- START_HIGHLIGHT -->

      <% if session[:user_id] %>
        <br />
        <%= link_to 'Orders',   orders_path   %><br />
        <%= link_to 'Products', products_path %><br />
        <%= link_to 'Users',    users_path    %><br />
        <br />
        <%= button_to 'Logout', logout_path, :method => :delete   %>
      <% end %>
<!-- END_HIGHLIGHT -->
      
      
    </div>
    <div id="main">
      <%= yield %><!-- <label id="code.depot.e.include"/> -->
    </div>
  </div>
</body>
</html>